### ISSUE TITLE
compiling fails on windows 10

### ISSUE THREAD

**Issue by dmbr0** [fhunleth/webengine_kiosk#28]
when I try to run my application the compilation fails. I have added build tools and nmake to the path. 

It appears it is looking for a Makefile.win

NMAKE : fatal error U1052: file 'Makefile.win' not found
Stop.
could not compile dependency :webengine_kiosk, "mix compile" failed. You can recompile this dependency with "mix deps.compile webengine_kiosk", update it with "mix deps.update webengine_kiosk" or clean it with "mix deps.clean webengine_kiosk"
==> elixir_desktop_application
** (Mix) Could not compile with "nmake" (exit status: 2).
One option is to install a recent version of
[Visual C++ Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools)
either manually or using [Chocolatey](https://chocolatey.org/) -
`choco install VisualCppBuildTools`.

I have added a blank one to the webengine_kiosk deps directory

NMAKE : fatal error U1073: don't know how to make 'all'
Stop.

I copied the Makefile to Makefile.win

Makefile.win(3) : fatal error U1000: syntax error : ')' missing in macro invocation
Stop.

Any ideas on how to make this work?

**Comment by fhunleth** [comment]
Sorry, no one has gotten this library to work on Windows. The error that you received is the default Elixir make one, so it's not helpful. 

Is it possible for you to use Linux or OSX? Perhaps the Windows Subsystem for Linux?
